pub mod all;
mod strings;
mod general_info;
mod chunk_writing;
mod fonts;
mod sounds;
mod embedded_audio;
mod scripts;
mod texture_page_items;
mod embedded_textures;
mod functions;
mod game_objects;
mod stubs;
mod sprites;
mod sequence;
mod backgrounds;
mod paths;
mod rooms;
