# Note: This needs the nightly channel to work.
#
# To format this workspace correctly:
# 1. `rustup toolchain install nightly`
# 2. `rustup component add rustfmt --toolchain nightly`
# 3. `cargo +nightly fmt --all`


# Stable Options
newline_style = "Unix"
struct_lit_width = 40
use_field_init_shorthand = true

# Nightly Options
float_literal_trailing_zero = "IfNoPostfix"
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Item"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
wrap_comments = true

